# Generated by Django 5.2.7 on 2025-11-05 09:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(db_index=True, max_length=10, unique=True)),
                ('db_name', models.CharField(db_index=True, default='temp', help_text='Database name where replicated data will be stored', max_length=20, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, db_index=True, max_length=100)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('replication_enabled', models.BooleanField(default=False, help_text='Enable real-time replication for this client')),
                ('replication_status', models.CharField(choices=[('not_configured', 'Not Configured'), ('configured', 'Configured'), ('active', 'Active'), ('paused', 'Paused'), ('error', 'Error')], default='not_configured', max_length=20)),
                ('last_replication_at', models.DateTimeField(blank=True, help_text='Last time data was replicated', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'client',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(db_index=True, max_length=100)),
                ('db_type', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('sqlite', 'SQLite'), ('oracle', 'Oracle')], default='mysql', max_length=20)),
                ('host', models.CharField(db_index=True, max_length=255)),
                ('port', models.PositiveIntegerField(default=3306)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('database_name', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=True, help_text='Is this the primary database for replication?')),
                ('connection_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('inactive', 'Inactive')], default='success', max_length=20)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='client.client')),
            ],
            options={
                'verbose_name': 'Client Database',
                'verbose_name_plural': 'Client Databases',
                'db_table': 'client_databases',
                'ordering': ['-created_at'],
            },
        ),
    ]
