# Generated by Django 5.2.7 on 2025-11-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablemapping',
            name='sync_frequency',
            field=models.CharField(blank=True, choices=[('realtime', 'Real-time (CDC)'), ('every_1min', 'Every 1 minute'), ('every_5min', 'Every 5 minutes'), ('every_15min', 'Every 15 minutes'), ('every_30min', 'Every 30 minutes'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('manual', 'Manual Only')], help_text='Leave empty to inherit from ReplicationConfig', max_length=20),
        ),
    ]
