# Generated by Django 5.2.7 on 2025-12-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdatabase',
            name='db_type',
            field=models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('sqlite', 'SQLite'), ('oracle', 'Oracle'), ('mssql', 'SQL Server')], default='mysql', max_length=20),
        ),
    ]
