# Generated by Django 5.2.7 on 2025-11-09 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='replicationconfig',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='columnmapping',
            name='source_type',
            field=models.CharField(blank=True, help_text='Source column data type (e.g., VARCHAR(255), INT, BIGINT)', max_length=100),
        ),
        migrations.AddField(
            model_name='columnmapping',
            name='target_type',
            field=models.CharField(blank=True, help_text='Target column data type', max_length=100),
        ),
        migrations.AddField(
            model_name='columnmapping',
            name='transformation_rule',
            field=models.TextField(blank=True, help_text='Optional transformation rule (SQL expression or function)', null=True),
        ),
        migrations.AlterField(
            model_name='columnmapping',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Whether this column should be replicated'),
        ),
        migrations.AlterField(
            model_name='columnmapping',
            name='is_nullable',
            field=models.BooleanField(default=True, help_text='Can this column contain NULL values'),
        ),
        migrations.AlterField(
            model_name='columnmapping',
            name='is_primary_key',
            field=models.BooleanField(default=False, help_text='Is this column part of the primary key'),
        ),
        migrations.AlterField(
            model_name='columnmapping',
            name='source_column',
            field=models.CharField(help_text='Source column name', max_length=255),
        ),
        migrations.AlterField(
            model_name='columnmapping',
            name='source_data_type',
            field=models.CharField(blank=True, help_text='Deprecated: use source_type instead', max_length=100),
        ),
        migrations.AlterField(
            model_name='columnmapping',
            name='table_mapping',
            field=models.ForeignKey(help_text='Parent table mapping', on_delete=django.db.models.deletion.CASCADE, related_name='column_mappings', to='client.tablemapping'),
        ),
        migrations.AlterField(
            model_name='columnmapping',
            name='target_column',
            field=models.CharField(help_text='Target column name (can be different from source)', max_length=255),
        ),
        migrations.AlterField(
            model_name='columnmapping',
            name='target_data_type',
            field=models.CharField(blank=True, help_text='Deprecated: use target_type instead', max_length=100),
        ),
        migrations.AlterField(
            model_name='columnmapping',
            name='transform_function',
            field=models.CharField(choices=[('none', 'No Transformation'), ('encrypt', 'Encrypt'), ('hash', 'Hash (SHA256)'), ('mask', 'Mask (e.g., XXX-XX-1234)'), ('uppercase', 'Convert to Uppercase'), ('lowercase', 'Convert to Lowercase'), ('trim', 'Trim Whitespace'), ('null_to_default', 'Convert NULL to Default')], default='none', help_text='Transformation to apply to column data', max_length=50),
        ),
        migrations.AlterField(
            model_name='replicationconfig',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='replicationconfig',
            name='status',
            field=models.CharField(choices=[('configured', 'Configured'), ('active', 'Active'), ('paused', 'Paused'), ('error', 'Error'), ('disabled', 'Disabled')], default='configured', max_length=20),
        ),
        migrations.AlterField(
            model_name='tablemapping',
            name='conflict_resolution',
            field=models.CharField(choices=[('source_wins', 'Source Always Wins'), ('target_wins', 'Target Always Wins'), ('newest_wins', 'Newest Timestamp Wins'), ('manual', 'Manual Resolution')], default='source_wins', help_text='How to handle conflicts during sync', max_length=20),
        ),
        migrations.AlterField(
            model_name='tablemapping',
            name='target_table',
            field=models.CharField(help_text="Table name in client's database (can be different from source)", max_length=255),
        ),
        migrations.AddIndex(
            model_name='columnmapping',
            index=models.Index(fields=['table_mapping', 'is_enabled'], name='column_mapp_table_m_22871f_idx'),
        ),
    ]
