# Generated by Django 5.2.7 on 2025-11-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='replicationconfig',
            name='connector_state',
            field=models.CharField(blank=True, help_text='Debezium connector state (RUNNING/PAUSED/FAILED/etc)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='replicationconfig',
            name='consumer_last_heartbeat',
            field=models.DateTimeField(blank=True, help_text='Last heartbeat from consumer (updated every 30s)', null=True),
        ),
        migrations.AddField(
            model_name='replicationconfig',
            name='consumer_state',
            field=models.CharField(default='UNKNOWN', help_text='Kafka consumer state (RUNNING/STOPPED/ERROR)', max_length=50),
        ),
        migrations.AddField(
            model_name='replicationconfig',
            name='consumer_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for running consumer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='replicationconfig',
            name='last_error_message',
            field=models.TextField(blank=True, help_text='Last error message for debugging', null=True),
        ),
    ]
