# Generated by Django 5.2.7 on 2025-11-09 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_replicationconfig_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdatabase',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_databases', to='client.client'),
        ),
    ]
