# Generated by Django 5.2.7 on 2025-11-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_clientdatabase_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdatabase',
            name='is_target',
            field=models.BooleanField(default=False, help_text='Indicates if this is the target database for replication'),
        ),
    ]
