# Generated by Django 5.2.7 on 2025-11-03 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_email_alter_client_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientDatabase',
        ),
    ]
