# Generated by Django 5.2.7 on 2025-11-03 08:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_delete_clientdatabase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(max_length=100)),
                ('db_type', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('sqlite', 'SQLite'), ('oracle', 'Oracle')], default='mysql', max_length=20)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=3306)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('database_name', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=True)),
                ('connection_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('inactive', 'Inactive')], default='success', max_length=20)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='client.client')),
            ],
        ),
    ]
