# Generated by Django 5.2.7 on 2025-11-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_clientdatabase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='db_name',
            field=models.CharField(db_index=True, default='temp', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='clientdatabase',
            name='connection_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='clientdatabase',
            name='host',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
