# Generated by Django 5.2.7 on 2025-11-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_encrypt_existing_passwords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='clientdatabase',
            options={'ordering': ['-created_at'], 'verbose_name': 'Client Database', 'verbose_name_plural': 'Client Databases'},
        ),
        migrations.AddField(
            model_name='client',
            name='last_replication_at',
            field=models.DateTimeField(blank=True, help_text='Last time data was replicated', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='replication_enabled',
            field=models.BooleanField(default=False, help_text='Enable real-time replication for this client'),
        ),
        migrations.AddField(
            model_name='client',
            name='replication_status',
            field=models.CharField(choices=[('not_configured', 'Not Configured'), ('configured', 'Configured'), ('active', 'Active'), ('paused', 'Paused'), ('error', 'Error')], default='not_configured', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='db_name',
            field=models.CharField(db_index=True, default='temp', help_text='Database name where replicated data will be stored', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='clientdatabase',
            name='is_primary',
            field=models.BooleanField(default=True, help_text='Is this the primary database for replication?'),
        ),
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
        migrations.AlterModelTable(
            name='clientdatabase',
            table='client_databases',
        ),
    ]
