"""
Django settings for jovoclient project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import pymysql
import os
pymysql.install_as_MySQLdb()
from dotenv import load_dotenv

load_dotenv(".env")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-sd-&4j-s=6t(tj47cyr2fzx2&yn9r5+pu(8#_foh&u@9s8$oqs')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 'yes')




ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    #third party app
    'tailwind',
    'theme',
    'django_cotton',
    'django_celery_beat',
    'django_celery_results',
   
    # local app
    'client',
    
]


if DEBUG:
    # Add django_browser_reload only in DEBUG mode
    INSTALLED_APPS += ['django_browser_reload']
    


MIDDLEWARE = [    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]


if DEBUG:
    # Add django_browser_reload middleware only in DEBUG mode
    MIDDLEWARE += [
        "django_browser_reload.middleware.BrowserReloadMiddleware",
    ]
    

ROOT_URLCONF = 'jovoclient.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jovoclient.wsgi.application'



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'test'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'CONN_MAX_AGE': 600,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

TAILWIND_APP_NAME = 'theme'

NPM_BIN_PATH = os.getenv("NPM_BIN_PATH","/usr/local/bin/npm")




# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000000
# Database password encryption key (symmetric encryption)
# TODO: Move this to environment variable in production
DB_PASSWORD_ENCRYPTION_KEY = 'your-32-byte-encryption-key-change-this-in-production!!'


# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Your SMTP server
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'jovo@kaybeebio.com'
EMAIL_HOST_PASSWORD = 'dchj gcgb hbgh xraf'
DEFAULT_FROM_EMAIL = 'noreply@yourcompany.com'

# Admin emails for error notifications
ADMINS = [
    ('Admin', 'jovo@kaybeebio.com'),
    ('Dev Team', 'dev@example.com'),
]

# Environment identifier
ENVIRONMENT = 'development'  # or 'staging', 'production'



LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': 'logs/replication.log',
            'when': 'H',                # Rotate every hour
            'interval': 1,              # 1 hour
            'backupCount': 48,          # Keep last 48 hours (optional)
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },  
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'client.utils': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}



# ====================================
# CELERY CONFIGURATION
# ====================================
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kolkata'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000
CELERY_WORKER_PREFETCH_MULTIPLIER = 4

# Celery Beat (for scheduled tasks)
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# ====================================
# DEBEZIUM / KAFKA CONFIGURATION
# ====================================
DEBEZIUM_CONFIG = {
    'KAFKA_CONNECT_URL': os.getenv('KAFKA_CONNECT_URL', 'http://localhost:8083'),
    'KAFKA_BOOTSTRAP_SERVERS': os.getenv('KAFKA_BOOTSTRAP_SERVERS', 'localhost:9092'),
    'KAFKA_INTERNAL_SERVERS': os.getenv('KAFKA_BOOTSTRAP_SERVERS', 'kafka:29092'),  # For Docker internal
    'SCHEMA_REGISTRY_URL': os.getenv('SCHEMA_REGISTRY_URL', 'http://localhost:8081'),
    'CONSUMER_GROUP_PREFIX': 'cdc_consumer',
}

# ====================================
# KAFKA TOPIC CONFIGURATION
# ====================================
# These settings control how Kafka topics are created and managed
# Can be overridden via environment variables for different environments
KAFKA_TOPIC_CONFIG = {
    # Number of partitions per topic
    # - 1 partition = strict message ordering (recommended for CDC)
    # - Multiple partitions = higher throughput but no ordering guarantee
    # Override: KAFKA_TOPIC_PARTITIONS=3
    'PARTITIONS': int(os.getenv('KAFKA_TOPIC_PARTITIONS', '1')),

    # Replication factor (number of copies)
    # - Must be <= number of Kafka brokers
    # - 1 broker (dev) = replication factor 1
    # - 3+ brokers (prod) = replication factor 2 or 3
    # Override: KAFKA_TOPIC_REPLICATION_FACTOR=3
    'REPLICATION_FACTOR': int(os.getenv('KAFKA_TOPIC_REPLICATION_FACTOR', '1')),

    # Retention time in milliseconds
    # How long Kafka keeps messages before deletion
    # - 1 hour = 3600000
    # - 1 day = 86400000
    # - 7 days = 604800000 (default, recommended for CDC)
    # - 30 days = 2592000000
    # - Forever = -1
    # Override: KAFKA_TOPIC_RETENTION_MS=2592000000
    'RETENTION_MS': int(os.getenv('KAFKA_TOPIC_RETENTION_MS', '604800000')),  # 7 days default

    # Retention size in bytes per partition
    # Maximum size per partition before old messages are deleted
    # -1 = unlimited (default)
    # Override: KAFKA_TOPIC_RETENTION_BYTES=1073741824
    'RETENTION_BYTES': int(os.getenv('KAFKA_TOPIC_RETENTION_BYTES', '-1')),

    # Cleanup policy
    # - 'delete': Delete old messages after retention period (recommended for CDC)
    # - 'compact': Keep only latest value per key
    # Override: KAFKA_TOPIC_CLEANUP_POLICY=compact
    'CLEANUP_POLICY': os.getenv('KAFKA_TOPIC_CLEANUP_POLICY', 'delete'),

    # Compression type
    # - 'none': No compression (fastest, uses most disk)
    # - 'gzip': Good compression, moderate CPU
    # - 'snappy': Balanced (recommended)
    # - 'lz4': Fast compression/decompression
    # - 'zstd': Best compression ratio
    # Override: KAFKA_TOPIC_COMPRESSION=lz4
    'COMPRESSION_TYPE': os.getenv('KAFKA_TOPIC_COMPRESSION_TYPE', 'snappy'),

    # Minimum in-sync replicas
    # Number of replicas that must acknowledge write before success
    # Must be <= replication factor
    # - 1 broker = 1
    # - 3 brokers with RF=3 = 2 (recommended for production)
    # Override: KAFKA_TOPIC_MIN_ISR=2
    'MIN_INSYNC_REPLICAS': int(os.getenv('KAFKA_TOPIC_MIN_ISR', '1')),

    # Segment size in bytes
    # Kafka rolls to new log segment after this size
    # Default: 1GB (1073741824)
    # Override: KAFKA_TOPIC_SEGMENT_BYTES=536870912
    'SEGMENT_BYTES': int(os.getenv('KAFKA_TOPIC_SEGMENT_BYTES', '1073741824')),

    # Segment time in milliseconds
    # Kafka rolls to new log segment after this time
    # Default: 7 days (604800000)
    # Override: KAFKA_TOPIC_SEGMENT_MS=86400000
    'SEGMENT_MS': int(os.getenv('KAFKA_TOPIC_SEGMENT_MS', '604800000')),
}
